[Icon Theme]
Name=HyperOS 3
Comment=HyperOS 3 icon theme (work in progress)
Inherits=Reversal,Adwaita,hicolor
Example=folder

# Fill these directories as you add icons (e.g., apps, actions, places)
# Directories entries are optional but recommended for gtk-update-icon-cache
Directories=apps/128,status/24

[apps/128]
Size=128
Context=Applications
Type=Fixed

[status/24]
Size=24
Context=Status
Type=Fixed

